FROM python:3.7

ADD ./baserow /baserow
ADD ./graph-visualization /graph-visualization
WORKDIR /graph-visualization

ENV PYTHONPATH $PYTHONPATH:/graph-visualization:/graph-visualization/plugins/graph_visualization/backend/src
ENV DJANGO_SETTINGS_MODULE='settings.dev'

RUN apt-get update
RUN apt-get -y install make
RUN apt-get -y install curl
RUN apt-get -y install gnupg2

RUN make install-python-dependencies
RUN make install-python-dev-dependencies

CMD tail -f /dev/null
