FROM node:10

ADD ./baserow /baserow
ADD ./graph-visualization /graph-visualization
WORKDIR /graph-visualization

RUN apt-get update
RUN apt-get -y install make
RUN apt-get -y install curl
RUN apt-get -y install gnupg2

CMD tail -f /dev/null
