version: "3"

services:
  db:
    container_name: graph-visualization-db
    image: postgres:11.3
    environment:
      - POSTGRES_USER=baserow
      - POSTGRES_PASSWORD=baserow
      - POSTGRES_DB=baserow
    ports:
      - 5432:5432

  redis:
    container_name: graph-visualization-redis
    image: redis:6.0
    ports:
      - 6379:6379

  mjml:
    container_name: graph-visualization-mjml
    image: liminspace/mjml-tcpserver:latest
    ports:
      - 28101:28101

  backend:
    container_name: graph-visualization-backend
    build:
      context: ../
      dockerfile: graph-visualization/Dockerfile.backend
    volumes:
      - ../baserow:/baserow
      - ./:/graph-visualization
    ports:
      - 8001:8000
    depends_on:
      - db
      - redis
      - mjml
    environment:
      - PUBLIC_BACKEND_URL=http://localhost:8001
      - PUBLIC_WEB_FRONTEND_URL=http://localhost:3001

  web-frontend:
    container_name: graph-visualization-web-frontend
    build:
      context: ../
      dockerfile: graph-visualization/Dockerfile.web-frontend
    volumes:
      - ../baserow:/baserow
      - ./:/graph-visualization
    ports:
      - 3001:3000
    depends_on:
      - backend
    environment:
      - PUBLIC_BACKEND_URL=http://localhost:8001
      - PUBLIC_WEB_FRONTEND_URL=http://localhost:3001

networks:
  default:
    external:
      name: baserow_plugin_default
