# Generated by Django 2.2.11 on 2021-04-13 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0029_phonenumberfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphView',
            fields=[
                ('view_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.View')),
            ],
            options={
                'abstract': False,
            },
            bases=('database.view',),
        ),
    ]
